version: '3.7'

services:
    site:
        container_name: karsten-lloyd-site
        image: docker.chester-lloyd.dev:5000/karsten/site:2024.04.23b
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 80:3000
