import Head from "next/head";
import { fetchExperience } from "../../lib/apollo";
import { Experience } from "../../types/graphql/experience";
import MainLayout from "../../components/layouts/mainLayout";
import { CardRow } from "../../components/cardRow";
import { Header } from "../../components/header";

export async function getStaticProps(): Promise<{
  props: PortfolioExperienceProps;
}> {
  const data = await fetchExperience();
  return {
    props: {
      experiences: data.experiences,
    },
  };
}

type PortfolioExperienceProps = {
  experiences: Experience[];
};

const PortfolioExperience = ({ experiences }: PortfolioExperienceProps) => (
  <>
    <Head>
      <title>Portfolio</title>
      <meta
        key="description"
        name="description"
        content="Generated by create next app"
      />
      <meta
        key="responsive"
        name="viewport"
        content="width=device-width, initial-scale=1"
      />
      <link key="favicon" rel="icon" href="/favicon.ico" />
    </Head>

    <Header
      title="Experience"
      breadcrumbs={[
        {
          name: "Portfolio",
          url: "/portfolio",
        },
      ]}
    />

    <div className="container">
      <CardRow
        title="Experience"
        showTitle={false}
        cards={experiences.map((experience: Experience) => ({
          title: experience.company,
          body: experience.description,
          colour: experience.colour,
          date_from: experience.date_from,
          date_to: experience.date_to,
          slug: experience.slug,
          key: experience.slug,
          type: "experience",
          specifications: {
            specs: [
              {
                name: "Languages",
                details: experience.languages
                  .map(
                    (experience_language) => experience_language.language.name
                  )
                  .join(", "),
              },
              {
                name: "Frameworks",
                details: experience.frameworks
                  .map(
                    (experience_framework) =>
                      experience_framework.framework.name
                  )
                  .join(", "),
              },
              {
                name: "Tools",
                details: experience.tools
                  .map((experience_tool) => experience_tool.tool.name)
                  .join(", "),
              },
              {
                name: "Services",
                details: experience.services
                  .map((experience_service) => experience_service.service.name)
                  .join(", "),
              },
            ],
            isTable: false,
            hasLinks: experience.url != null,
          },
          footer: {
            text: experience.company,
            link: experience.url,
            backgroundColour: experience.colour,
          },
        }))}
      />
    </div>
  </>
);

PortfolioExperience.layout = MainLayout;

export default PortfolioExperience;
