import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import HomeLayout from "../components/layouts/homeLayout";
import styles from "../components/index/index.module.css";
import { Jumbotron } from "../components/index/jumbotron";
import { IconRow } from "../components/index/iconRow";
import Waves from "../components/index/waves";

const Home: NextPageWithLayout = () => (
  <>
    <Head>
      <title>Karsten Lloyd</title>
      <meta
        key="description"
        name="description"
        content="Generated by create next app"
      />
      <meta
        key="responsive"
        name="viewport"
        content="width=device-width, initial-scale=1"
      />
      <link key="favicon" rel="icon" href="/favicon.ico" />
    </Head>

    <Waves />

    <div className={styles.homeContainer}>
      <div className="container">
        <div className="row justify-content-center">
          <div className="col-sm-12 col-md-8 col-lg-6">
            <Jumbotron />
          </div>
        </div>
        <div className="row justify-content-center mt-4">
          <div className="col-sm-12 col-md-8 col-lg-6">
            <div className="row">
              <div className="text-center col-12">
                <IconRow />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </>
);

Home.getLayout = function getLayout(Home: ReactElement) {
  return <HomeLayout>{Home}</HomeLayout>;
};

export default Home;
